### PR TITLE
rename to juttle-service

### PR DESCRIPTION
**Pull request by demmer**
Big rename of all files and internal classes to reflect the change from
"juttle engine" to "juttle service".

### CODE REVIEW

**Comment by demmer** [comment]
@mstemm

**Comment by go-oleg** [comment]
a few remaining ones (all except the first should be changed to service):
```
~/git/juttle/juttle-engine (rename-to-juttle-service)$ grep -ir "engine" *
README.md:juttle-service is an API-based execution engine for juttle programs.
bin/juttle-service-client:opts.juttle_engine = opts['juttle-service'];
bin/juttle-service-client:var juttled_ws_url = 'ws://' + opts.juttle_engine + API_PREFIX;
bin/juttle-service-client:var juttled_noapi_ws_url = 'ws://' + opts.juttle_engine;
bin/juttle-service-client:var juttled_http_url = 'http://' + opts.juttle_engine + API_PREFIX;
docs/jobs-api.md:# Juttle Engine API
lib/juttle-service.js:            logger.info('Juttle engine listening at http://localhost:' + options.port + ' with root directory:' + options.root_directory);
package.json:  "description": "API-based execution engine for juttle programs",
test/juttle-service.spec.js:describe('Juttle Engine Tests', function() {
```

otherwise :+1:

**Comment by demmer** [comment]
@go-oleg thanks -- I pushed a commit that fixes those last few.

**Comment by go-oleg** [comment]
looks good

**Pull request merged**
